apiVersion: apps/v1
kind: deployment
metadata:
  name: docker-app-deployment
  namespace: docker-project
spec:
  selector:
    matchLabels:
      app: spring-boot-k8s
  replicas: 4
  template:
    metadata:
      labels:
        app: spring-boot-k8s
    spec:
      containers:
        -name: docker-app-container
        image: dockerapp:2.0
        imagePullPolicy: IfNotPresent
        ports:
          -containerPort: 8282
