apiVersion: v1
kind: Service
metadata:
  name: docker-app-service
  namespace : docker-project
spec:
  selector:
    app: spring-boot-k8s
  ports:
    -protocol: TCP
    port: 9090
    targetPort: 8282
  type: NodePort
